version: '3'

volumes:
  django_app_local_postgres_data: {}
  django_app_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_app_local_django
    container_name: django_app_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "80:80"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_app_production_postgres
    container_name: django_app_local_postgres
    volumes:
      - django_app_local_postgres_data:/var/lib/postgresql/data:Z
      - django_app_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    container_name: django_app_local_mailhog
    restart: unless-stopped
    restart: always
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025 



